CREATE TABLE PRODUCT (
    PROD_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PROD_NAME NVARCHAR(20) NOT NULL,
    PROD_DESC NVARCHAR(MAX) NOT NULL,
    PROD_PRICE DECIMAL(10, 2) NOT NULL,
    PROD_CATE_ID INT NOT NULL,
    PROD_IMG_URL VARCHAR(2083) NULL,
    PROD_LIST_TIME DATETIME2(0) NOT NULL CONSTRAINT DF_ProductListTime DEFAULT GETUTCDATE(),
    -- 外來键约束（尚未建立類別表）
    --CONSTRAINT FK_Product_Category FOREIGN KEY (PROD_CATE_ID)
    --    REFERENCES PRODUCT_CATEGORY(CATE_ID)
);
-- 索引（依照實際查询需求添加）
CREATE INDEX IX_Product_Category ON PRODUCT(PROD_CATE_ID);
CREATE INDEX IX_Product_ListTime ON PRODUCT(PROD_LIST_TIME);
