CREATE TABLE PRODUCT (
    PROD_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PROD_NAME NVARCHAR(50) NOT NULL,
    PROD_DESC NVARCHAR(MAX) NOT NULL,
    PROD_PRICE DECIMAL(10, 2) NOT NULL,
    PROD_CATE_ID INT NOT NULL,
    PROD_IMG_URL VARCHAR(2083) NULL,
    PROD_LIST_TIME DATETIME2(0) NOT NULL CONSTRAINT DF_ProductListTime DEFAULT GETUTCDATE(),
    -- ═══════ 約束 ═══════
    -- 1.建立參考FK：PRODUCT_CATEGORY的CATE_ID
    --CONSTRAINT FK_Product_Category FOREIGN KEY (PROD_CATE_ID)
    --    REFERENCES PRODUCT_CATEGORY(CATE_ID)
);

CREATE TABLE PRODUCT_CATEGORY (
    CATE_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CATE_NAME NVARCHAR(50) NOT NULL,
    PARENT_CATE_ID INT NULL,
    CATE_DESC NVARCHAR(500) NULL,
    CREATED_AT DATETIME2(0) NOT NULL DEFAULT GETUTCDATE(),
    -- ═══════ 約束 ═══════
    
    -- 1. 確保分類名不重複
    CONSTRAINT UQ_ProductCategory_Name UNIQUE (CATE_NAME),
    
    -- 2. 自我參考FK，允許階層結構
    --    允許 PARENT_CATE_ID 為 NULL，表示頂層分類
    CONSTRAINT FK_ProductCategory_Parent FOREIGN KEY (PARENT_CATE_ID)
        REFERENCES PRODUCT_CATEGORY(CATE_ID)
);
