CREATE TABLE ORDERS(
	order_id INT PRIMARY KEY IDENTITY(1,1),
	order_date DATETIME NOT NULL,
	sku_id INT NOT NULL,
	quantity INT NOT NULL,
	subtotal_price DECIMAL(10,2) NOT NULL,
	total_price DECIMAL(10,2) NOT NULL,
	memid INT NOT NULL,

	FOREIGN KEY (SKU_ID) REFERENCES PRODUCT_SKUS(SKU_ID),
    FOREIGN KEY (MEMID) REFERENCES MEM(MEMID)
	);


CREATE TABLE ORDER_SHIPPING(
	ORDER_ID INT PRIMARY KEY,
	REC_NAME NVARCHAR(20) NOT NULL,
	REC_ADR NVARCHAR(50) NOT NULL,
	REC_TEL VARCHAR(20) NOT NULL,
	REC_MAIL VARCHAR(50) NOT NULL,
	SEN_ADR NVARCHAR(50) NOT NULL,
	SEN_NAME NVARCHAR(20) NOT NULL,

	FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);
