CREATE TABLE [MEM](
	MEMid INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MEMNAME NVARCHAR(20) NULL,
	MEMGD NVARCHAR(10) NOT NULL,
	MEMPN NVARCHAR(20) NULL,
	MEMIN NVARCHAR(10) NULL,
	MEMADR NVARCHAR(50) NULL,
	MEMMAIL NVARCHAR(50) NULL,
	MEMBD DATE NULL,
	MEMDCT DATETIME NOT NULL DEFAULT GETDATE(),
	MEMACC NVARCHAR(10) NULL,
        MEMUPDATEDBY NVARCHAR(50) NULL,                  
        MEMUPDATEDAT DATETIME DEFAULT GETDATE()           
);
SELECT * FROM MEM;

CREATE TABLE [MEM_AUDIT] (
    AuditID INT IDENTITY(1,1) PRIMARY KEY,
    MEMid INT,
    MEMNAME NVARCHAR(20),
    MEMGD NVARCHAR(10),
    MEMPN NVARCHAR(20),
    MEMIN NVARCHAR(10),
    MEMADR NVARCHAR(50),
    MEMMAIL NVARCHAR(50),
    MEMBD DATE,
    MEMDCT DATETIME,
    MEMACC NVARCHAR(10),
    MEMUPDATEDBY NVARCHAR(50),
    MEMUPDATEDAT DATETIME,
    AuditTime DATETIME DEFAULT GETDATE(),             -- 稽核時間
    AuditAction NVARCHAR(10)                          -- 動作類型，如：UPDATE
);

--觸發器

CREATE TRIGGER TR_MEM_UPDATE_AUDIT
ON [MEM]
AFTER UPDATE
AS
BEGIN
    INSERT INTO [MEM_AUDIT] (
        MEMid, MEMNAME, MEMGD, MEMPN, MEMIN, MEMADR, MEMMAIL, MEMBD,
        MEMDCT, MEMACC, MEMUPDATEDBY, MEMUPDATEDAT, AuditAction
    )
    SELECT 
        d.MEMid, d.MEMNAME, d.MEMGD, d.MEMPN, d.MEMIN, d.MEMADR, d.MEMMAIL, d.MEMBD,
        d.MEMDCT, d.MEMACC, d.MEMUPDATEDBY, d.MEMUPDATEDAT, 'UPDATE'
    FROM deleted d;
END;
