CREATE TABLE [MEM](
	MEMid INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MEMNAME NVARCHAR(20) NULL,
	MEMGD NVARCHAR(10) NOT NULL,
	MEMPN NVARCHAR(20) NULL,
	MEMIN NVARCHAR(10) NULL,
	MEMADR NVARCHAR(50) NULL,
	MEMMAIL NVARCHAR(50) NULL,
	MEMBD DATE NULL,
	MEMDCT DATETIME NOT NULL DEFAULT GETDATE(),
	MEMACC NVARCHAR(10) NULL,
        MEMUPDATEDBY NVARCHAR(50) NULL,                  
        MEMUPDATEDAT DATETIME DEFAULT GETDATE()           
);
SELECT * FROM MEM;