--1.新增MEM_RANK
CREATE TABLE MEM_RANK (
    RANKID INT PRIMARY KEY NOT NULL,
    RANKNAME NVARCHAR(20) NOT NULL
);
--2.新增DEP
CREATE TABLE DEP (
    DEPID INT PRIMARY KEY NOT NULL,
    DEPNAME NVARCHAR(20) NOT NULL,
    MGRID INT  -- 先不加 FK
);
--3.新增EMP
CREATE TABLE EMP (
    EMPID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    EMPNAME NVARCHAR(20) NOT NULL,
    EMPPN INT NOT NULL,
    EMPMAIL NVARCHAR(50) NOT NULL,
    EMPDCT DATETIME,
    EMPACC NVARCHAR(10),
    DEPID INT NOT NULL,
    EMPPW VARCHAR(255),
    EMPUPDATEBY INT,
    EMPUPDATEAT DATETIME,
    FOREIGN KEY (DEPID) REFERENCES DEP(DEPID),
    FOREIGN KEY (EMPUPDATEBY) REFERENCES EMP(EMPID)
);
--4.新增DEP的FK
ALTER TABLE DEP
ADD CONSTRAINT FK_DEP_MGRID FOREIGN KEY (MGRID) REFERENCES EMP(EMPID);
--5.新增MEM
CREATE TABLE [MEM](
	MEMid INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MEMNAME NVARCHAR(20) NOT NULL,
    MEMGD VARCHAR(10),
    MEMPN NVARCHAR(15) NOT NULL,
    MEMIN NVARCHAR(10),
    MEMADR NVARCHAR(50) NOT NULL,
    MEMMAIL NVARCHAR(50) NOT NULL,
    MEMBD DATE NOT NULL,
    MEMPW VARCHAR(255),  -- 存加密密碼
    MEMDCT DATETIME,
    RANKID INT,
    MEMUPDATEBY INT,
    MEMUPDATEAT DATETIME,
    GIFTTOUSERID INT,
    FOREIGN KEY (RANKID) REFERENCES MEM_RANK(RANKID),
    FOREIGN KEY (MEMUPDATEBY) REFERENCES EMP(EMPID)     
);

---下面不重要
SELECT name FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('EMP');
SELECT name FROM sys.foreign_keys WHERE parent_object_id = OBJECT_ID('MEM');

--刪表方法
ALTER TABLE DEP DROP CONSTRAINT FK_DEP_MGRID;
ALTER TABLE EMP DROP CONSTRAINT FK__EMP__EMPUPDATEBY__3D5E1FD2;
ALTER TABLE EMP DROP CONSTRAINT FK__EMP__DEPID__3C69FB99;
ALTER TABLE MEM DROP CONSTRAINT FK__MEM__MEMUPDATEBY__4222D4EF;

DROP TABLE EMP;
DROP TABLE DEP;
